name: Add existing issues to the project board

on: [workflow_dispatch]

jobs:
  call_add_existing_issues_workflow:
    uses: informatics-isi-edu/isrd-github-workflows/.github/workflows/add-existing-issues-to-project.yml@main
    with:
      PROJECT_NUMBER: #Add the project number for the project board.
      REPO_NAME: #Add the repository name with the issues. Example: isrd-github-workflows
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
